// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entity.Migrations.PostgresDb
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.DocumentInfraction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("PaymentAgreementId")
                        .HasColumnType("integer")
                        .HasColumnName("PaymentAgreementId");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("inspectoraReportId")
                        .HasColumnType("integer")
                        .HasColumnName("inspectoraReportId");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("PaymentAgreementId");

                    b.HasIndex("inspectoraReportId");

                    b.ToTable("DocumentInfraction", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            PaymentAgreementId = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            inspectoraReportId = 1,
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            PaymentAgreementId = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            inspectoraReportId = 2,
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.InspectoraReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("report_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("total_fines")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("id");

                    b.ToTable("InspectoraReport", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "se integra una nueva multa",
                            report_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_fines = 2m
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "se integra una nueva multa",
                            report_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_fines = 3m
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypeInfraction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("numer_smldv")
                        .HasColumnType("integer");

                    b.Property<string>("type_Infraction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("type_Infraction")
                        .IsUnique();

                    b.ToTable("typeInfraction", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "lanzar basura en un lugar publico",
                            is_deleted = false,
                            numer_smldv = 4,
                            type_Infraction = "infraccion de tipo uno"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "hacer mucho ruido en un sitio publico",
                            is_deleted = false,
                            numer_smldv = 8,
                            type_Infraction = "infraccion de tipo dos"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Portar armas, elementos cortantes, punzantes, o sustancias peligrosas en áreas comunes o lugares abiertos al público.",
                            is_deleted = false,
                            numer_smldv = 16,
                            type_Infraction = "infraccion de tipo Tres"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Agresión a la autoridad: Agredir o lanzar objetos a las autoridades de policía.",
                            is_deleted = false,
                            numer_smldv = 32,
                            type_Infraction = "infraccion de tipo Cuatro"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypePayment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("paymentAgreementId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("typePayment", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "efectivo",
                            paymentAgreementId = 0
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "nequi",
                            paymentAgreementId = 0
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "tarjeta crédito",
                            paymentAgreementId = 0
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "tarjeta débito",
                            paymentAgreementId = 0
                        },
                        new
                        {
                            id = 5,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "daviplata",
                            paymentAgreementId = 0
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserInfraction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserNotificationId")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("amountToPay")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dateInfraction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("stateInfraction")
                        .HasColumnType("integer");

                    b.Property<int>("typeInfractionId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserNotificationId");

                    b.HasIndex("typeInfractionId");

                    b.ToTable("userInfraction", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            UserId = 1,
                            UserNotificationId = 1,
                            active = true,
                            amountToPay = 0m,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dateInfraction = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            observations = "la persona no opuso resistencia a la infracción",
                            stateInfraction = 0,
                            typeInfractionId = 1
                        },
                        new
                        {
                            id = 2,
                            UserId = 1,
                            UserNotificationId = 2,
                            active = true,
                            amountToPay = 0m,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dateInfraction = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            observations = "portaba un cuchillo en la vía pública",
                            stateInfraction = 0,
                            typeInfractionId = 3
                        },
                        new
                        {
                            id = 3,
                            UserId = 2,
                            UserNotificationId = 1,
                            active = true,
                            amountToPay = 0m,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dateInfraction = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            observations = "la persona se encontraba en estado de embriaguez",
                            stateInfraction = 0,
                            typeInfractionId = 2
                        },
                        new
                        {
                            id = 4,
                            UserId = 2,
                            UserNotificationId = 2,
                            active = true,
                            amountToPay = 0m,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dateInfraction = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            observations = "agredió verbalmente a la autoridad",
                            stateInfraction = 0,
                            typeInfractionId = 4
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("shippingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("userNotification", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "tienes una infraccion por favor acercate antes del 12 de marzo para sucdazanar tu multa o podria iniciar un cobro coativo luego del plazo",
                            shippingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "tienes una infraccion por favor acercate antes del 12 de julio para sucdazanar tu multa o podria iniciar un cobro coativo luego del plazo",
                            shippingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.ValueSmldv", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Current_Year")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("minimunWage")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("value_smldv")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("id");

                    b.HasIndex("Current_Year")
                        .IsUnique();

                    b.ToTable("valueSmldv", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Current_Year = 2024,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            minimunWage = 1300000m,
                            value_smldv = 43500m
                        },
                        new
                        {
                            id = 2,
                            Current_Year = 2022,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            minimunWage = 1100000m,
                            value_smldv = 43500m
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Form", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("form", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Formulario de creacion de acuerdo de pago",
                            is_deleted = false,
                            name = "Formulario de acuerdo de pago"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Formulario para agregar nuevas multas",
                            is_deleted = false,
                            name = "Formulario de creacion de multas"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.FormModule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("formid")
                        .HasColumnType("integer")
                        .HasColumnName("formid");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("moduleid")
                        .HasColumnType("integer")
                        .HasColumnName("moduleid");

                    b.HasKey("id");

                    b.HasIndex("formid");

                    b.HasIndex("moduleid");

                    b.ToTable("formmodule", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formid = 1,
                            is_deleted = false,
                            moduleid = 1
                        },
                        new
                        {
                            id = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formid = 2,
                            is_deleted = false,
                            moduleid = 2
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Module", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("module", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Módulo para administración general",
                            is_deleted = false,
                            name = "Módulo de hacienda"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Módulo encargado de crear nuevas multas",
                            is_deleted = false,
                            name = "Módulo de inspectora"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "modulo encargado para visualizar las multas inspuestas",
                            is_deleted = false,
                            name = "Modulo de usuario"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("permission", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para leer formularios",
                            is_deleted = false,
                            name = "Leer"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para crear formularios",
                            is_deleted = false,
                            name = "Crear"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para editar formularios",
                            is_deleted = false,
                            name = "Editar"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para eliminar lógicamente formularios",
                            is_deleted = false,
                            name = "Eliminar"
                        },
                        new
                        {
                            id = 5,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para ver formularios eliminados",
                            is_deleted = false,
                            name = "VerEliminados"
                        },
                        new
                        {
                            id = 6,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para recuperar formularios eliminados",
                            is_deleted = false,
                            name = "Recuperar"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<string>("address")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("municipalityId")
                        .HasColumnType("integer");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("tipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("municipalityId");

                    b.ToTable("person", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            firstName = "Juan",
                            is_deleted = false,
                            lastName = "Pérez",
                            municipalityId = 1,
                            tipoUsuario = 3
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            firstName = "Sara",
                            is_deleted = false,
                            lastName = "Sofía",
                            municipalityId = 4,
                            tipoUsuario = 3
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("rol", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Rol con todos los permisos",
                            is_deleted = false,
                            name = "Administrador"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Rol estándar para usuarios normales",
                            is_deleted = false,
                            name = "Usuario"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("documentNumber")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("documentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("documentTypeId");

                    b.ToTable("user", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            EmailVerified = true,
                            EmailVerifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "admin123",
                            PersonId = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            documentNumber = "1234567890",
                            documentTypeId = 1,
                            email = "camiloandreslosada901@gmail.com",
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            EmailVerified = true,
                            EmailVerifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "sara12312",
                            PersonId = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            documentNumber = "0123432121",
                            documentTypeId = 2,
                            email = "sarita@gmail.com",
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.PaymentFrequency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("dueDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<string>("intervalPage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("intervalPage");

                    b.ToTable("paymentFrequency", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 16,
                            intervalPage = "UNICA",
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 15,
                            intervalPage = "MENSUAL",
                            is_deleted = false
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 1,
                            intervalPage = "QUINCENAL",
                            is_deleted = false
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 10,
                            intervalPage = "BIMESTRAL",
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("daneCode")
                        .HasColumnType("integer");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("id");

                    b.HasIndex("daneCode")
                        .IsUnique();

                    b.HasIndex("name");

                    b.ToTable("department", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 5,
                            is_deleted = false,
                            name = "Antioquia"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 25,
                            is_deleted = false,
                            name = "Cundinamarca"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 76,
                            is_deleted = false,
                            name = "Valle del Cauca"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 11,
                            is_deleted = false,
                            name = "Bogotá, D.C."
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.documentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("id");

                    b.HasIndex("abbreviation")
                        .IsUnique();

                    b.HasIndex("name");

                    b.ToTable("documentType", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            abbreviation = "CC",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            id = 2,
                            abbreviation = "CE",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Cédula de Extranjería"
                        },
                        new
                        {
                            id = 3,
                            abbreviation = "TI",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            id = 4,
                            abbreviation = "PAS",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Pasaporte"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.municipality", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("daneCode")
                        .HasColumnType("integer");

                    b.Property<int>("departmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("id");

                    b.HasIndex("daneCode")
                        .IsUnique();

                    b.HasIndex("name");

                    b.HasIndex("departmentId", "name")
                        .IsUnique();

                    b.ToTable("municipality", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 5001,
                            departmentId = 1,
                            is_deleted = false,
                            name = "Medellín"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 76001,
                            departmentId = 3,
                            is_deleted = false,
                            name = "Cali"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 11001,
                            departmentId = 4,
                            is_deleted = false,
                            name = "Bogotá"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 25754,
                            departmentId = 2,
                            is_deleted = false,
                            name = "Soacha"
                        });
                });

            modelBuilder.Entity("FineCalculationDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("formula")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("totalCalculation")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("typeInfractionId")
                        .HasColumnType("integer");

                    b.Property<int>("valueSmldvId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("typeInfractionId");

                    b.HasIndex("valueSmldvId");

                    b.ToTable("FineCalculationDetail", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formula = "salario minimo * dias = smdlv",
                            is_deleted = false,
                            totalCalculation = 0m,
                            typeInfractionId = 1,
                            valueSmldvId = 1
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formula = "salario minimo * dias = smdlv",
                            is_deleted = false,
                            totalCalculation = 0m,
                            typeInfractionId = 2,
                            valueSmldvId = 1
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formula = "salario minimo * dias = smdlv",
                            is_deleted = false,
                            totalCalculation = 0m,
                            typeInfractionId = 3,
                            valueSmldvId = 1
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formula = "salario minimo * dias = smdlv",
                            is_deleted = false,
                            totalCalculation = 0m,
                            typeInfractionId = 4,
                            valueSmldvId = 1
                        });
                });

            modelBuilder.Entity("PaymentAgreement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("AccruedInterest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("AgreementDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("AgreementEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AgreementStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CoactiveActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Installments")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCoactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastInterestAppliedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expeditionCedula")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("neighborhood")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("paymentFrequencyId")
                        .HasColumnType("integer");

                    b.Property<int>("typePaymentId")
                        .HasColumnType("integer");

                    b.Property<int>("userInfractionId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("paymentFrequencyId");

                    b.HasIndex("typePaymentId");

                    b.HasIndex("userInfractionId");

                    b.ToTable("paymentAgreement", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AccruedInterest = 0m,
                            AgreementDescription = "se realizará a 4 cuotas iguales",
                            AgreementEnd = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AgreementStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BaseAmount = 130500m,
                            Email = "user1@example.com",
                            Installments = 4,
                            IsCoactive = false,
                            IsPaid = false,
                            MonthlyFee = 32625m,
                            OutstandingAmount = 130500m,
                            PhoneNumber = "3101234567",
                            active = true,
                            address = "carrera 10",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            expeditionCedula = new DateTime(2016, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            neighborhood = "eduardo santos",
                            paymentFrequencyId = 1,
                            typePaymentId = 1,
                            userInfractionId = 1
                        },
                        new
                        {
                            id = 2,
                            AccruedInterest = 0m,
                            AgreementDescription = "se realizará a 2 cuotas iguales",
                            AgreementEnd = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AgreementStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BaseAmount = 174000m,
                            Email = "user2@example.com",
                            Installments = 2,
                            IsCoactive = false,
                            IsPaid = false,
                            MonthlyFee = 87000m,
                            OutstandingAmount = 174000m,
                            PhoneNumber = "3009876543",
                            active = true,
                            address = "carrera 1",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            expeditionCedula = new DateTime(2017, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            neighborhood = "panamá",
                            paymentFrequencyId = 2,
                            typePaymentId = 2,
                            userInfractionId = 2
                        },
                        new
                        {
                            id = 3,
                            AccruedInterest = 0m,
                            AgreementDescription = "se realizará a 8 cuotas iguales",
                            AgreementEnd = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AgreementStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BaseAmount = 348000m,
                            Email = "user3@example.com",
                            Installments = 8,
                            IsCoactive = false,
                            IsPaid = false,
                            MonthlyFee = 43500m,
                            OutstandingAmount = 348000m,
                            PhoneNumber = "3015558888",
                            active = true,
                            address = "calle 20 #15-40",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            expeditionCedula = new DateTime(2018, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            neighborhood = "la merced",
                            paymentFrequencyId = 2,
                            typePaymentId = 3,
                            userInfractionId = 3
                        },
                        new
                        {
                            id = 4,
                            AccruedInterest = 0m,
                            AgreementDescription = "se realizará a 12 cuotas iguales",
                            AgreementEnd = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AgreementStart = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BaseAmount = 835200m,
                            Email = "user4@example.com",
                            Installments = 12,
                            IsCoactive = false,
                            IsPaid = false,
                            MonthlyFee = 69600m,
                            OutstandingAmount = 835200m,
                            PhoneNumber = "3024449999",
                            active = true,
                            address = "avenida 5 #45-12",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            expeditionCedula = new DateTime(2019, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            neighborhood = "san martin",
                            paymentFrequencyId = 3,
                            typePaymentId = 1,
                            userInfractionId = 4
                        });
                });

            modelBuilder.Entity("RolFormPermission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("formid");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permissionid");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rolid");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("FormId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RolId", "FormId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolFormPermission_Unique");

                    b.ToTable("rolformpermission", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FormId = 1,
                            PermissionId = 1,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            FormId = 1,
                            PermissionId = 2,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 3,
                            FormId = 1,
                            PermissionId = 3,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 4,
                            FormId = 1,
                            PermissionId = 4,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 5,
                            FormId = 1,
                            PermissionId = 1,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 6,
                            FormId = 1,
                            PermissionId = 2,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 7,
                            FormId = 1,
                            PermissionId = 3,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 8,
                            FormId = 1,
                            PermissionId = 4,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 9,
                            FormId = 1,
                            PermissionId = 5,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 10,
                            FormId = 1,
                            PermissionId = 6,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("RolUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rolId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("roluser", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            RolId = 1,
                            UserId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            RolId = 2,
                            UserId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.DocumentInfraction", b =>
                {
                    b.HasOne("PaymentAgreement", "paymentAgreement")
                        .WithMany("documentInfraction")
                        .HasForeignKey("PaymentAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentInfraction_PaymentAgreement");

                    b.HasOne("Entity.Domain.Models.Implements.Entities.InspectoraReport", "inspectoraReport")
                        .WithMany("documentInfraction")
                        .HasForeignKey("inspectoraReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentInfraction_InspectoraReport");

                    b.Navigation("inspectoraReport");

                    b.Navigation("paymentAgreement");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserInfraction", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.User", "User")
                        .WithMany("UserInfraction")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Domain.Models.Implements.Entities.UserNotification", "UserNotification")
                        .WithMany("userInfraction")
                        .HasForeignKey("UserNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Domain.Models.Implements.Entities.TypeInfraction", "typeInfraction")
                        .WithMany("userInfractions")
                        .HasForeignKey("typeInfractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserNotification");

                    b.Navigation("typeInfraction");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.FormModule", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Form", "form")
                        .WithMany("FormModules")
                        .HasForeignKey("formid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FormModule_Form");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Module", "module")
                        .WithMany("FormModules")
                        .HasForeignKey("moduleid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FormModule_Module");

                    b.Navigation("form");

                    b.Navigation("module");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Person", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.parameters.municipality", "municipality")
                        .WithMany("person")
                        .HasForeignKey("municipalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("municipality");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.User", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Entity.Domain.Models.Implements.ModelSecurity.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_User_Person");

                    b.HasOne("Entity.Domain.Models.Implements.parameters.documentType", "documentType")
                        .WithMany("person")
                        .HasForeignKey("documentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");

                    b.Navigation("documentType");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.municipality", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.parameters.department", "department")
                        .WithMany("Municipality")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("FineCalculationDetail", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.Entities.TypeInfraction", "typeInfraction")
                        .WithMany("fineCalculationDetail")
                        .HasForeignKey("typeInfractionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TypeInfraction_FineCalculationDetail");

                    b.HasOne("Entity.Domain.Models.Implements.Entities.ValueSmldv", "valueSmldv")
                        .WithMany("fineCalculationDetail")
                        .HasForeignKey("valueSmldvId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ValueSmldv_FineCalculationDetail");

                    b.Navigation("typeInfraction");

                    b.Navigation("valueSmldv");
                });

            modelBuilder.Entity("PaymentAgreement", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.parameters.PaymentFrequency", "paymentFrequency")
                        .WithMany("paymentAgreement")
                        .HasForeignKey("paymentFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entity.Domain.Models.Implements.Entities.TypePayment", "TypePayment")
                        .WithMany("PaymentAgreements")
                        .HasForeignKey("typePaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentAgreement_TypePayment");

                    b.HasOne("Entity.Domain.Models.Implements.Entities.UserInfraction", "userInfraction")
                        .WithMany("paymentAgreement")
                        .HasForeignKey("userInfractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentAgreement_UserInfraction");

                    b.Navigation("TypePayment");

                    b.Navigation("paymentFrequency");

                    b.Navigation("userInfraction");
                });

            modelBuilder.Entity("RolFormPermission", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Form", "Form")
                        .WithMany("rol_form_permission")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Form");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Permission", "Permission")
                        .WithMany("rol_form_permission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Permission");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Rol", "Rol")
                        .WithMany("rol_form_permission")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Rol");

                    b.Navigation("Form");

                    b.Navigation("Permission");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RolUser", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Rol", "Rol")
                        .WithMany("rolUsers")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUser_Rol");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.User", "User")
                        .WithMany("rolUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUser_User");

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.InspectoraReport", b =>
                {
                    b.Navigation("documentInfraction");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypeInfraction", b =>
                {
                    b.Navigation("fineCalculationDetail");

                    b.Navigation("userInfractions");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypePayment", b =>
                {
                    b.Navigation("PaymentAgreements");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserInfraction", b =>
                {
                    b.Navigation("paymentAgreement");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserNotification", b =>
                {
                    b.Navigation("userInfraction");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.ValueSmldv", b =>
                {
                    b.Navigation("fineCalculationDetail");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Form", b =>
                {
                    b.Navigation("FormModules");

                    b.Navigation("rol_form_permission");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Module", b =>
                {
                    b.Navigation("FormModules");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Permission", b =>
                {
                    b.Navigation("rol_form_permission");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Rol", b =>
                {
                    b.Navigation("rolUsers");

                    b.Navigation("rol_form_permission");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.User", b =>
                {
                    b.Navigation("UserInfraction");

                    b.Navigation("rolUsers");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.PaymentFrequency", b =>
                {
                    b.Navigation("paymentAgreement");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.department", b =>
                {
                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.documentType", b =>
                {
                    b.Navigation("person");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.municipality", b =>
                {
                    b.Navigation("person");
                });

            modelBuilder.Entity("PaymentAgreement", b =>
                {
                    b.Navigation("documentInfraction");
                });
#pragma warning restore 612, 618
        }
    }
}
