// <auto-generated />
using System;
using Entity.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.DocumentInfraction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("PaymentAgreementId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentAgreementId");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("inspectoraReportId")
                        .HasColumnType("int")
                        .HasColumnName("inspectoraReportId");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("PaymentAgreementId");

                    b.HasIndex("inspectoraReportId");

                    b.ToTable("DocumentInfraction", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            PaymentAgreementId = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            inspectoraReportId = 1,
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            PaymentAgreementId = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            inspectoraReportId = 2,
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.InspectoraReport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("report_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("total_fines")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("InspectoraReport", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "se integra una nueva multa",
                            report_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_fines = 2m
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "se integra una nueva multa",
                            report_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            total_fines = 3m
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.PaymentAgreement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AgreementDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("neighborhood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("paymentFrequencyId")
                        .HasColumnType("int");

                    b.Property<int>("userInfractionId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("paymentFrequencyId");

                    b.HasIndex("userInfractionId");

                    b.ToTable("paymentAgreement", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AgreementDescription = "se realizará a 4 cuotas de 200.000 los 15 de cada mes desde este momento",
                            active = true,
                            address = "carrera 10",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            neighborhood = "eduardo santos",
                            paymentFrequencyId = 1,
                            userInfractionId = 1
                        },
                        new
                        {
                            id = 2,
                            AgreementDescription = "se realizará a 2 cuotas de 50.000 los 12 de cada mes desde este momento",
                            active = true,
                            address = "carrera 1",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            neighborhood = "panamá",
                            paymentFrequencyId = 2,
                            userInfractionId = 2
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypeInfraction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("numer_smldv")
                        .HasColumnType("int");

                    b.Property<string>("type_Infraction")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("type_Infraction")
                        .IsUnique();

                    b.ToTable("typeInfraction", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "lanzar basura en un lugar publico",
                            is_deleted = false,
                            numer_smldv = 2,
                            type_Infraction = "infraccion de tipo uno"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "hacer mucho ruido en un sitio publico",
                            is_deleted = false,
                            numer_smldv = 4,
                            type_Infraction = "infraccion de tipo dos"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Portar armas, elementos cortantes, punzantes, o sustancias peligrosas en áreas comunes o lugares abiertos al público.",
                            is_deleted = false,
                            numer_smldv = 8,
                            type_Infraction = "infraccion de tipo Tres"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Agresión a la autoridad: Agredir o lanzar objetos a las autoridades de policía. ",
                            is_deleted = false,
                            numer_smldv = 16,
                            type_Infraction = "infraccion de tipo Cuatro"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypePayment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("paymentAgreementId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("paymentAgreementId");

                    b.ToTable("typePayment", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "efectivo",
                            paymentAgreementId = 1
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "nequi",
                            paymentAgreementId = 2
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserInfraction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserNotificationId")
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<decimal>("amountToPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateInfraction")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("observations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("stateInfraction")
                        .HasColumnType("bit");

                    b.Property<int>("typeInfractionId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserNotificationId");

                    b.HasIndex("typeInfractionId");

                    b.ToTable("userInfraction", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            UserId = 1,
                            UserNotificationId = 1,
                            active = true,
                            amountToPay = 0m,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dateInfraction = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            observations = "la persona no opuso resistencia a la infraccion",
                            stateInfraction = false,
                            typeInfractionId = 1
                        },
                        new
                        {
                            id = 2,
                            UserId = 2,
                            UserNotificationId = 2,
                            active = true,
                            amountToPay = 0m,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dateInfraction = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            observations = "la persona se encontraba en estado de embriagues",
                            stateInfraction = false,
                            typeInfractionId = 2
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserNotification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("shippingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("userNotification", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "tienes una infraccion por favor acercate antes del 12 de marzo para sucdazanar tu multa o podria iniciar un cobro coativo luego del plazo",
                            shippingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            message = "tienes una infraccion por favor acercate antes del 12 de julio para sucdazanar tu multa o podria iniciar un cobro coativo luego del plazo",
                            shippingDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.ValueSmldv", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Current_Year")
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("minimunWage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("value_smldv")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("Current_Year")
                        .IsUnique();

                    b.ToTable("valueSmldv", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Current_Year = 2024,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            minimunWage = 1300000m,
                            value_smldv = 43.5
                        },
                        new
                        {
                            id = 2,
                            Current_Year = 2022,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            minimunWage = 1100000m,
                            value_smldv = 43.5
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.AuthSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("AbsoluteExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("AuthSession", "ModelSecurity");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Form", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("form", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Formulario de creacion de acuerdo de pago",
                            is_deleted = false,
                            name = "Formulario de acuerdo de pago"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Formulario para agregar nuevas multas",
                            is_deleted = false,
                            name = "Formulario de creacion de multas"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.FormModule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("formid")
                        .HasColumnType("int")
                        .HasColumnName("formid");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("moduleid")
                        .HasColumnType("int")
                        .HasColumnName("moduleid");

                    b.HasKey("id");

                    b.HasIndex("formid");

                    b.HasIndex("moduleid");

                    b.ToTable("formmodule", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formid = 1,
                            is_deleted = false,
                            moduleid = 1
                        },
                        new
                        {
                            id = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formid = 2,
                            is_deleted = false,
                            moduleid = 2
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Module", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("module", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Módulo para administración general",
                            is_deleted = false,
                            name = "Módulo de hacienda"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Módulo encargado de crear nuevas multas",
                            is_deleted = false,
                            name = "Módulo de inspectora"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "modulo encargado para visualizar las multas inspuestas",
                            is_deleted = false,
                            name = "Modulo de usuario"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("permission", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para leer formularios",
                            is_deleted = false,
                            name = "Leer"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para crear formularios",
                            is_deleted = false,
                            name = "Crear"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para editar formularios",
                            is_deleted = false,
                            name = "Editar"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para eliminar lógicamente formularios",
                            is_deleted = false,
                            name = "Eliminar"
                        },
                        new
                        {
                            id = 5,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para ver formularios eliminados",
                            is_deleted = false,
                            name = "VerEliminados"
                        },
                        new
                        {
                            id = 6,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "permiso para recuperar formularios eliminados",
                            is_deleted = false,
                            name = "Recuperar"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("address")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("municipalityId")
                        .HasColumnType("int");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("tipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("municipalityId");

                    b.HasIndex("phoneNumber")
                        .IsUnique()
                        .HasFilter("[phoneNumber] IS NOT NULL");

                    b.ToTable("person", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            address = "Carrera 10",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            firstName = "Juan",
                            is_deleted = false,
                            lastName = "Pérez",
                            municipalityId = 1,
                            phoneNumber = "1234567890",
                            tipoUsuario = 3
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            address = "Carrera 11",
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            firstName = "Sara",
                            is_deleted = false,
                            lastName = "Sofía",
                            municipalityId = 4,
                            phoneNumber = "312312314",
                            tipoUsuario = 3
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("rol", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Rol con todos los permisos",
                            is_deleted = false,
                            name = "Administrador"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            description = "Rol estándar para usuarios normales",
                            is_deleted = false,
                            name = "Usuario"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("documentNumber")
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("documentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.HasIndex("documentTypeId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("user", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            EmailVerified = true,
                            EmailVerifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "admin123",
                            PersonId = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            documentNumber = "123456789",
                            documentTypeId = 1,
                            email = "camiloandreslosada901@gmail.com",
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            EmailVerified = true,
                            EmailVerifiedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "sara12312",
                            PersonId = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            documentNumber = "0123432121",
                            documentTypeId = 2,
                            email = "sarita@gmail.com",
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.PaymentFrequency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("dueDayOfMonth")
                        .HasColumnType("int");

                    b.Property<string>("intervalPage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("intervalPage");

                    b.ToTable("paymentFrequency", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 16,
                            intervalPage = "UNICA",
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 15,
                            intervalPage = "MENSUAL",
                            is_deleted = false
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 1,
                            intervalPage = "QUINCENAL",
                            is_deleted = false
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dueDayOfMonth = 10,
                            intervalPage = "BIMESTRAL",
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("daneCode")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("id");

                    b.HasIndex("daneCode")
                        .IsUnique();

                    b.HasIndex("name");

                    b.ToTable("department", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 5,
                            is_deleted = false,
                            name = "Antioquia"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 25,
                            is_deleted = false,
                            name = "Cundinamarca"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 76,
                            is_deleted = false,
                            name = "Valle del Cauca"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 11,
                            is_deleted = false,
                            name = "Bogotá, D.C."
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.documentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("id");

                    b.HasIndex("abbreviation")
                        .IsUnique();

                    b.HasIndex("name");

                    b.ToTable("documentType", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            abbreviation = "CC",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            id = 2,
                            abbreviation = "CE",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Cédula de Extranjería"
                        },
                        new
                        {
                            id = 3,
                            abbreviation = "TI",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            id = 4,
                            abbreviation = "PAS",
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false,
                            name = "Pasaporte"
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.municipality", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("daneCode")
                        .HasColumnType("int");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("id");

                    b.HasIndex("daneCode")
                        .IsUnique();

                    b.HasIndex("name");

                    b.HasIndex("departmentId", "name")
                        .IsUnique();

                    b.ToTable("municipality", "Parameters");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 5001,
                            departmentId = 1,
                            is_deleted = false,
                            name = "Medellín"
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 76001,
                            departmentId = 3,
                            is_deleted = false,
                            name = "Cali"
                        },
                        new
                        {
                            id = 3,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 11001,
                            departmentId = 4,
                            is_deleted = false,
                            name = "Bogotá"
                        },
                        new
                        {
                            id = 4,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            daneCode = 25754,
                            departmentId = 2,
                            is_deleted = false,
                            name = "Soacha"
                        });
                });

            modelBuilder.Entity("FineCalculationDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("formula")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("porcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("totalCalculation")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("typeInfractionId")
                        .HasColumnType("int");

                    b.Property<int>("valueSmldvId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("typeInfractionId");

                    b.HasIndex("valueSmldvId");

                    b.ToTable("FineCalculationDetail", "Entities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formula = "salario minimo * dias = smdlv",
                            is_deleted = false,
                            porcentaje = 0.5m,
                            totalCalculation = 100000m,
                            typeInfractionId = 1,
                            valueSmldvId = 1
                        },
                        new
                        {
                            id = 2,
                            active = true,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            formula = "salario minimo * dias = smdlv",
                            is_deleted = false,
                            porcentaje = 0.0m,
                            totalCalculation = 150.000m,
                            typeInfractionId = 2,
                            valueSmldvId = 2
                        });
                });

            modelBuilder.Entity("RolFormPermission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("formid");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permissionid");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rolid");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("FormId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RolId", "FormId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolFormPermission_Unique");

                    b.ToTable("rolformpermission", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            FormId = 1,
                            PermissionId = 1,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            FormId = 1,
                            PermissionId = 2,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 3,
                            FormId = 1,
                            PermissionId = 3,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 4,
                            FormId = 1,
                            PermissionId = 4,
                            RolId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 5,
                            FormId = 1,
                            PermissionId = 1,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 6,
                            FormId = 1,
                            PermissionId = 2,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 7,
                            FormId = 1,
                            PermissionId = 3,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 8,
                            FormId = 1,
                            PermissionId = 4,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 9,
                            FormId = 1,
                            PermissionId = 5,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 10,
                            FormId = 1,
                            PermissionId = 6,
                            RolId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("RolUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rolId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("RolId");

                    b.HasIndex("UserId");

                    b.ToTable("roluser", "ModelSecurity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            RolId = 1,
                            UserId = 1,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        },
                        new
                        {
                            id = 2,
                            RolId = 2,
                            UserId = 2,
                            active = false,
                            created_date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            is_deleted = false
                        });
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.DocumentInfraction", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.Entities.PaymentAgreement", "paymentAgreement")
                        .WithMany("documentInfraction")
                        .HasForeignKey("PaymentAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentInfraction_PaymentAgreement");

                    b.HasOne("Entity.Domain.Models.Implements.Entities.InspectoraReport", "inspectoraReport")
                        .WithMany("documentInfraction")
                        .HasForeignKey("inspectoraReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DocumentInfraction_InspectoraReport");

                    b.Navigation("inspectoraReport");

                    b.Navigation("paymentAgreement");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.PaymentAgreement", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.parameters.PaymentFrequency", "paymentFrequency")
                        .WithMany("paymentAgreement")
                        .HasForeignKey("paymentFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entity.Domain.Models.Implements.Entities.UserInfraction", "userInfraction")
                        .WithMany("paymentAgreement")
                        .HasForeignKey("userInfractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentAgreement_UserInfraction");

                    b.Navigation("paymentFrequency");

                    b.Navigation("userInfraction");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypePayment", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.Entities.PaymentAgreement", "PaymentAgreement")
                        .WithMany("typePayments")
                        .HasForeignKey("paymentAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TypePayment_PaymentAgreement");

                    b.Navigation("PaymentAgreement");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserInfraction", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.User", "User")
                        .WithMany("UserInfraction")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Domain.Models.Implements.Entities.UserNotification", "UserNotification")
                        .WithMany("userInfraction")
                        .HasForeignKey("UserNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Domain.Models.Implements.Entities.TypeInfraction", "typeInfraction")
                        .WithMany("userInfractions")
                        .HasForeignKey("typeInfractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserNotification");

                    b.Navigation("typeInfraction");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.FormModule", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Form", "form")
                        .WithMany("FormModules")
                        .HasForeignKey("formid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FormModule_Form");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Module", "module")
                        .WithMany("FormModules")
                        .HasForeignKey("moduleid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_FormModule_Module");

                    b.Navigation("form");

                    b.Navigation("module");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Person", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.parameters.municipality", "municipality")
                        .WithMany("person")
                        .HasForeignKey("municipalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("municipality");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.User", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Person", "Person")
                        .WithOne("User")
                        .HasForeignKey("Entity.Domain.Models.Implements.ModelSecurity.User", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_User_Person");

                    b.HasOne("Entity.Domain.Models.Implements.parameters.documentType", "documentType")
                        .WithMany("person")
                        .HasForeignKey("documentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Person");

                    b.Navigation("documentType");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.municipality", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.parameters.department", "department")
                        .WithMany("Municipality")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("FineCalculationDetail", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.Entities.TypeInfraction", "typeInfraction")
                        .WithMany("fineCalculationDetail")
                        .HasForeignKey("typeInfractionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TypeInfraction_FineCalculationDetail");

                    b.HasOne("Entity.Domain.Models.Implements.Entities.ValueSmldv", "valueSmldv")
                        .WithMany("fineCalculationDetail")
                        .HasForeignKey("valueSmldvId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ValueSmldv_FineCalculationDetail");

                    b.Navigation("typeInfraction");

                    b.Navigation("valueSmldv");
                });

            modelBuilder.Entity("RolFormPermission", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Form", "Form")
                        .WithMany("rol_form_permission")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Form");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Permission", "Permission")
                        .WithMany("rol_form_permission")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Permission");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Rol", "Rol")
                        .WithMany("rol_form_permission")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolFormPermission_Rol");

                    b.Navigation("Form");

                    b.Navigation("Permission");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RolUser", b =>
                {
                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.Rol", "Rol")
                        .WithMany("rolUsers")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUser_Rol");

                    b.HasOne("Entity.Domain.Models.Implements.ModelSecurity.User", "User")
                        .WithMany("rolUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolUser_User");

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.InspectoraReport", b =>
                {
                    b.Navigation("documentInfraction");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.PaymentAgreement", b =>
                {
                    b.Navigation("documentInfraction");

                    b.Navigation("typePayments");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.TypeInfraction", b =>
                {
                    b.Navigation("fineCalculationDetail");

                    b.Navigation("userInfractions");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserInfraction", b =>
                {
                    b.Navigation("paymentAgreement");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.UserNotification", b =>
                {
                    b.Navigation("userInfraction");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.Entities.ValueSmldv", b =>
                {
                    b.Navigation("fineCalculationDetail");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Form", b =>
                {
                    b.Navigation("FormModules");

                    b.Navigation("rol_form_permission");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Module", b =>
                {
                    b.Navigation("FormModules");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Permission", b =>
                {
                    b.Navigation("rol_form_permission");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Person", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.Rol", b =>
                {
                    b.Navigation("rolUsers");

                    b.Navigation("rol_form_permission");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.ModelSecurity.User", b =>
                {
                    b.Navigation("UserInfraction");

                    b.Navigation("rolUsers");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.PaymentFrequency", b =>
                {
                    b.Navigation("paymentAgreement");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.department", b =>
                {
                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.documentType", b =>
                {
                    b.Navigation("person");
                });

            modelBuilder.Entity("Entity.Domain.Models.Implements.parameters.municipality", b =>
                {
                    b.Navigation("person");
                });
#pragma warning restore 612, 618
        }
    }
}
